import { describe, it, expect, beforeAll, afterAll } from "vitest";
import {
  createPublicClient,
  createWalletClient,
  http,
  defineChain,
  encodeFunctionData,
  parseUnits,
  keccak256,
  toHex,
  type Address,
  type Hex,
} from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { existsSync, readFileSync } from "node:fs";

/**
 * Generated by `node scripts/e2e-setup.js` against a running hardhat node.
 * Loaded at RUNTIME, not as a static import: a missing file must skip this
 * suite, not crash the whole test run before a single test executes.
 */
const ADDRESSES_PATH = new URL("./e2e-addresses.json", import.meta.url);
export const HAS_E2E_FIXTURE = existsSync(ADDRESSES_PATH);
const addresses = HAS_E2E_FIXTURE
  ? JSON.parse(readFileSync(ADDRESSES_PATH, "utf8"))
  : // Placeholders so the module-scope viem clients below can still be
    // constructed when the suite is skipped. describe.skipIf keeps the tests
    // from running; it does not stop this file being imported.
    ({
      rpcUrl: "http://127.0.0.1:8545",
      chainId: 1337,
      integrator: "0x0000000000000000000000000000000000000001",
      diamond: "0x0000000000000000000000000000000000000002",
      client: "0x0000000000000000000000000000000000000003",
      usdc: "0x0000000000000000000000000000000000000004",
      relayerKey: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
      adminKey: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
    } as Record<string, any>);
import { handlePay } from "../src/pay";
import { handleRelayTx } from "../src/relayTx";
import { INTEGRATOR_ABI, type Env } from "../src/config";
import { readLink, linkBlockedReason } from "../src/chain";
import { makeTestEnv, mineBlocks, increaseTime, useLocalBundler, registerLinkAgent, CUSTOMER_PUBKEY, signRelayAction } from "./harness";

/**
 * End-to-end against a real chain.
 *
 * This drives the ACTUAL Worker handlers — `handlePay`, `handleRelayTx` — with
 * real HTTP Requests, a real RPC, real signing, and real receipts. The only
 * simulated pieces are the Cloudflare bindings (KV, Durable Objects), which the
 * harness reimplements faithfully enough that the concurrency behaviour under
 * test is the real behaviour.
 *
 * If this passes, the walletless payment path works.
 */

const chain = defineChain({
  id: addresses.chainId,
  name: "local",
  nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
  rpcUrls: { default: { http: [addresses.rpcUrl] } },
});

const pub = createPublicClient({ chain, transport: http(addresses.rpcUrl) });

// Hardhat account #1 — the merchant. Only used to create links, exactly as the
// merchant's own sponsored transaction would.
const MERCHANT_KEY = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d" as Hex;
const merchantWallet = createWalletClient({
  account: privateKeyToAccount(MERCHANT_KEY),
  chain,
  transport: http(addresses.rpcUrl),
});

const INR = toHex("INR", { size: 32 });
// A REAL keypair — see harness. The customer's key must now sign, not just
// receive, so a placeholder would test a path no real customer takes.
const PUBKEY = CUSTOMER_PUBKEY;
const USDC = (n: number) => parseUnits(String(n), 6);

let env: Env;

/**
 * Link ids must be unique per run: the contract refuses to overwrite an
 * existing link (LinkExists), so a fixed id would only work against a fresh
 * chain. This keeps the suite re-runnable against a long-lived node.
 */
const RUN = `${Date.now()}-${Math.random().toString(36).slice(2)}`;

/** Creates a link the way the merchant's browser would. */
async function createLink(opts: {
  id: string;
  amount: bigint;
  expiresAt?: bigint;
  /** Convenience: true means maxUses 1. */
  singleUse?: boolean;
  /** How many SUCCESSFUL payments the link takes. 0 = unlimited. */
  maxUses?: number;
  currency?: Hex;
}): Promise<Hex> {
  const linkId = keccak256(toHex(`${RUN}:${opts.id}`));
  const hash = await merchantWallet.writeContract({
    address: addresses.integrator as Address,
    abi: [
      {
        type: "function",
        name: "createLink",
        stateMutability: "nonpayable",
        inputs: [
          { name: "linkId", type: "bytes32" },
          { name: "amount", type: "uint96" },
          { name: "currency", type: "bytes32" },
          { name: "expiresAt", type: "uint64" },
          { name: "maxUses", type: "uint32" },
          { name: "encryptedConfig", type: "bytes" },
        ],
        outputs: [],
      },
    ] as const,
    functionName: "createLink",
    args: [
      linkId,
      opts.amount,
      opts.currency ?? INR,
      opts.expiresAt ?? 0n,
      opts.maxUses ?? (opts.singleUse ? 1 : 0),
      "0x" as Hex,
    ],
    account: merchantWallet.account!,
    chain,
  });
  await pub.waitForTransactionReceipt({ hash });

  // The link's own account, bound to it on the Router. In production the
  // merchant app batches this into the very operation that creates the link —
  // a link without it looks correctly created and can never be paid, so every
  // path that creates one must do this too.
  await registerLinkAgent(env, linkId, merchantWallet, addresses.router);

  return linkId;
}

/**
 * Exactly what the customer's browser POSTs when they tap Pay.
 *
 * Each request gets its own source IP by default — these are different
 * customers, and sharing one would trip the per-IP rate limit partway through
 * the suite and mask real failures. Pass a fixed `ip` to test the limiter.
 */
let ipCounter = 0;
function payRequest(body: Record<string, unknown> = {}, ip?: string): Request {
  const from = ip ?? `203.0.113.${(ipCounter++ % 200) + 1}`;
  return new Request("https://worker/api/pay/x", {
    method: "POST",
    headers: { "Content-Type": "application/json", "CF-Connecting-IP": from },
    body: JSON.stringify({ pubKey: PUBKEY, circleId: 1, ...body }),
  });
}

/**
 * The bundler and paymaster are SERVICES, not our code, so they are the only
 * thing substituted here. Everything in `src/` — packing the operation,
 * requesting sponsorship, reading the outcome flag — runs exactly as it will in
 * production, which is what keeps this suite able to catch a packing mistake
 * rather than agreeing with one.
 */
let bundlerHandle: ReturnType<typeof useLocalBundler>;
afterAll(() => bundlerHandle?.restore());

beforeAll(async () => {
  env = makeTestEnv(addresses);
  bundlerHandle = useLocalBundler(addresses);

  // The contract caps a merchant at 25 orders per UTC day, and link payments
  // count toward it — correct behaviour, but this suite places more than that.
  // Raise the ceiling so the tests exercise the payment path rather than
  // repeatedly re-proving the daily limit (which has its own dedicated test).
  const admin = createWalletClient({
    account: privateKeyToAccount(
      "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
    ),
    chain,
    transport: http(addresses.rpcUrl),
  });
  const hash = await admin.writeContract({
    address: addresses.integrator as Address,
    abi: [
      {
        type: "function",
        name: "setDailyLimit",
        stateMutability: "nonpayable",
        inputs: [{ type: "uint256" }],
        outputs: [],
      },
    ] as const,
    functionName: "setDailyLimit",
    args: [5000n],
    account: admin.account!,
    chain,
  });
  await pub.waitForTransactionReceipt({ hash });
});

describe.skipIf(!HAS_E2E_FIXTURE)("E2E · the walletless payment path", () => {
  it("a customer with no wallet pays a link and an order really exists on-chain", async () => {
    const linkId = await createLink({ id: "e2e-happy", amount: USDC(3), singleUse: true });

    const res = await handlePay(payRequest(), env, linkId);
    const body = (await res.json()) as { orderId?: string; txHash?: string; error?: string };

    expect(res.status, `unexpected: ${JSON.stringify(body)}`).toBe(200);
    expect(body.orderId).toBeDefined();
    expect(body.txHash).toMatch(/^0x[0-9a-f]{64}$/);

    // The order is recorded against the LINK'S OWNER — the merchant never
    // signed anything, and the customer has no wallet at all.
    const merchant = await pub.readContract({
      address: addresses.integrator as Address,
      abi: INTEGRATOR_ABI,
      functionName: "orderToMerchant",
      args: [BigInt(body.orderId!)],
    });
    expect((merchant as string).toLowerCase()).toBe(addresses.merchant.toLowerCase());
  });

  it("consumes a single-use link, so a forwarded URL is dead", async () => {
    const linkId = await createLink({ id: "e2e-single", amount: USDC(2), singleUse: true });

    const first = await handlePay(payRequest(), env, linkId);
    expect(first.status).toBe(200);

    // Someone else opens the same URL.
    const second = await handlePay(payRequest(), env, linkId);
    const body = (await second.json()) as { error: string };
    expect(second.status).toBe(409);
    expect(body.error).toMatch(/already been used/i);
  });

  it("keeps a reusable link payable, and each payment is its own order", async () => {
    const linkId = await createLink({ id: "e2e-reuse", amount: USDC(1), singleUse: false });

    const ids: string[] = [];
    for (let i = 0; i < 3; i++) {
      const res = await handlePay(payRequest(), env, linkId);
      expect(res.status).toBe(200);
      ids.push(((await res.json()) as { orderId: string }).orderId);
    }
    expect(new Set(ids).size).toBe(3);
  });

  it("refuses a revoked link the moment it is revoked — no cache to go stale", async () => {
    const linkId = await createLink({ id: "e2e-revoke", amount: USDC(1) });

    expect((await handlePay(payRequest(), env, linkId)).status).toBe(200);

    const hash = await merchantWallet.writeContract({
      address: addresses.integrator as Address,
      abi: [
        {
          type: "function",
          name: "revokeLink",
          stateMutability: "nonpayable",
          inputs: [{ name: "linkId", type: "bytes32" }],
          outputs: [],
        },
      ] as const,
      functionName: "revokeLink",
      args: [linkId],
      account: merchantWallet.account!,
      chain,
    });
    await pub.waitForTransactionReceipt({ hash });

    const res = await handlePay(payRequest(), env, linkId);
    expect(res.status).toBe(409);
    expect(((await res.json()) as { error: string }).error).toMatch(/cancelled/i);
  });

  it("refuses an expired link", async () => {
    const now = BigInt((await pub.getBlock()).timestamp);
    const linkId = await createLink({
      id: "e2e-expiry",
      amount: USDC(1),
      expiresAt: now + 60n,
    });

    expect((await handlePay(payRequest(), env, linkId)).status).toBe(200);

    await increaseTime(addresses.rpcUrl, 120);
    const res = await handlePay(payRequest(), env, linkId);
    expect(res.status).toBe(409);
    expect(((await res.json()) as { error: string }).error).toMatch(/expired/i);
  });

  it("tells the customer plainly when the merchant has hit their daily limit", async function () {
    // This really happened while building this suite: the merchant exhausted
    // their 25/day quota and every further payment failed. The customer is
    // alone with the screen, so the message has to say what is wrong.
    const admin = createWalletClient({
      account: privateKeyToAccount(
        "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
      ),
      chain,
      transport: http(addresses.rpcUrl),
    });
    const setLimit = async (n: bigint) => {
      const h = await admin.writeContract({
        address: addresses.integrator as Address,
        abi: [
          {
            type: "function",
            name: "setDailyLimit",
            stateMutability: "nonpayable",
            inputs: [{ type: "uint256" }],
            outputs: [],
          },
        ] as const,
        functionName: "setDailyLimit",
        args: [n],
        account: admin.account!,
        chain,
      });
      await pub.waitForTransactionReceipt({ hash: h });
    };

    const linkId = await createLink({ id: "e2e-daily", amount: USDC(1) });
    await setLimit(1n); // already used far more than 1 today
    try {
      const res = await handlePay(payRequest(), env, linkId);
      const { error } = (await res.json()) as { error: string };
      expect(res.status).toBe(409);
      expect(error).toMatch(/today's payment limit/i);
      expect(error).not.toMatch(/0x|revert/i);
    } finally {
      await setLimit(5000n);
    }
  });

  it("returns a message a person can act on, never a raw revert", async () => {
    const linkId = keccak256(toHex("never-created"));
    const res = await handlePay(payRequest(), env, linkId);
    const { error } = (await res.json()) as { error: string };

    expect(res.status).toBe(404);
    expect(error).toMatch(/not found/i);
    expect(error).not.toMatch(/0x|revert|execution/i);
  });
});

describe.skipIf(!HAS_E2E_FIXTURE)("E2E · the request body cannot move money", () => {
  it("ignores a tampered amount on a fixed-price link", async () => {
    const linkId = await createLink({ id: "e2e-tamper", amount: USDC(5), singleUse: true });

    // The customer's browser claims quantity 1 (= 1 USDC) for a 5 USDC link.
    // The Worker derives quantity from the link itself, so the order is 5 USDC.
    const res = await handlePay(payRequest({ quantity: 1 }), env, linkId);
    expect(res.status).toBe(200);

    const { orderId } = (await res.json()) as { orderId: string };
    const logs = await pub.getLogs({
      address: addresses.integrator as Address,
      event: INTEGRATOR_ABI.find(
        (e) => e.type === "event" && e.name === "LinkOrderPlaced"
      ) as never,
      fromBlock: 0n,
    });
    const mine = logs.find(
      (l) => (l as unknown as { args: { orderId: bigint } }).args.orderId === BigInt(orderId)
    ) as unknown as { args: { amount: bigint } };

    expect(mine.args.amount, "amount comes from the CHAIN, not the body").toBe(USDC(5));
  });

  it("rejects an absurd quantity on a variable link before spending gas", async () => {
    const linkId = await createLink({ id: "e2e-absurd", amount: 0n });

    // 1e30 passes Number.isInteger — the guard must be isSafeInteger.
    const res = await handlePay(payRequest({ quantity: 1e30 }), env, linkId);
    expect(res.status).toBe(400);
  });

  it("rejects a quantity above the merchant's per-tx cap", async () => {
    const linkId = await createLink({ id: "e2e-cap", amount: 0n });
    // Default INR cap is 50 USDC; ask for 500.
    const res = await handlePay(payRequest({ quantity: 500 }), env, linkId);
    expect(res.status).toBe(409);
    expect(((await res.json()) as { error: string }).error).toMatch(/above the limit/i);
  });

  it("requires a relay pubkey — the LP has nothing to encrypt to without it", async () => {
    const linkId = await createLink({ id: "e2e-nokey", amount: USDC(1) });
    const req = new Request("https://worker/api/pay/x", {
      method: "POST",
      headers: { "Content-Type": "application/json", "CF-Connecting-IP": "203.0.113.9" },
      body: JSON.stringify({ circleId: 1 }),
    });
    expect((await handlePay(req, env, linkId)).status).toBe(400);
  });

  it("rejects a malformed link id without touching the chain", async () => {
    expect((await handlePay(payRequest(), env, "not-a-link")).status).toBe(400);
  });
});

describe.skipIf(!HAS_E2E_FIXTURE)("E2E · concurrency", () => {
  it("two customers paying DIFFERENT links at once both succeed — the nonce bug", async () => {
    // This is the failure the global nonce sequencer exists to prevent: two
    // payments on different links read the same pending nonce, and one
    // transaction is silently dropped with no error anywhere.
    // Created sequentially — the MERCHANT's own wallet has no nonce sequencer,
    // and racing it here would test viem rather than the Worker. What must be
    // concurrent is the two PAYMENTS below, which is where the relayer's
    // single nonce sequence is actually contended.
    const a = await createLink({ id: "e2e-conc-a", amount: USDC(1) });
    const b = await createLink({ id: "e2e-conc-b", amount: USDC(1) });

    const [ra, rb] = await Promise.all([
      handlePay(payRequest(), env, a),
      handlePay(payRequest(), env, b),
    ]);

    const [ba, bb] = (await Promise.all([ra.json(), rb.json()])) as {
      orderId?: string;
      error?: string;
    }[];

    expect(ra.status, `A failed: ${ba.error}`).toBe(200);
    expect(rb.status, `B failed: ${bb.error}`).toBe(200);
    expect(ba.orderId).not.toBe(bb.orderId);

    // Both transactions really landed — neither was dropped.
    for (const id of [ba.orderId!, bb.orderId!]) {
      const m = await pub.readContract({
        address: addresses.integrator as Address,
        abi: INTEGRATOR_ABI,
        functionName: "orderToMerchant",
        args: [BigInt(id)],
      });
      expect(m).not.toBe("0x0000000000000000000000000000000000000000");
    }
  });

  it("a double-tap on ONE link places at most one order", async () => {
    const linkId = await createLink({ id: "e2e-doubletap", amount: USDC(1), singleUse: true });

    const [r1, r2] = await Promise.all([
      handlePay(payRequest(), env, linkId),
      handlePay(payRequest(), env, linkId),
    ]);

    const ok = [r1, r2].filter((r) => r.status === 200);
    expect(ok.length, "exactly one tap may win").toBe(1);
  });
});

describe.skipIf(!HAS_E2E_FIXTURE)("E2E · relay-tx forwarding", () => {
  let seq = 0;
  async function placeOrder(): Promise<string> {
    const linkId = await createLink({ id: `e2e-relay-${seq++}`, amount: USDC(1) });
    const res = await handlePay(payRequest(), env, linkId);
    const body = (await res.json()) as { orderId?: string; error?: string };
    expect(res.status, `pay failed: ${body.error}`).toBe(200);
    return body.orderId!;
  }

  let relaySeq = 0;
  function relayReq(to: string, data: string, signature?: string): Request {
    return new Request("https://worker/api/relay-tx", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "CF-Connecting-IP": `198.51.100.${(relaySeq++ % 200) + 1}`,
      },
      body: JSON.stringify({ to, data, ...(signature ? { signature } : {}) }),
    });
  }

  const cancelData = (orderId: bigint) =>
    encodeFunctionData({
      abi: [
        {
          type: "function",
          name: "cancelOrder",
          stateMutability: "nonpayable",
          inputs: [{ type: "uint256" }],
          outputs: [],
        },
      ] as const,
      functionName: "cancelOrder",
      args: [orderId],
    });

  it("refuses any target that is not the Diamond", async () => {
    const orderId = await placeOrder();
    // Pointed at our own integrator — the one thing this must never reach.
    const res = await handleRelayTx(
      relayReq(addresses.integrator, cancelData(BigInt(orderId))),
      env
    );
    expect(res.status).toBe(403);
  });

  it("refuses a selector that is not on the allowlist", async () => {
    const withdraw = encodeFunctionData({
      abi: [
        {
          type: "function",
          name: "withdrawUSDC",
          stateMutability: "nonpayable",
          inputs: [{ type: "uint256" }],
          outputs: [],
        },
      ] as const,
      functionName: "withdrawUSDC",
      args: [1n],
    });
    const res = await handleRelayTx(relayReq(addresses.diamond, withdraw), env);
    expect(res.status).toBe(403);
  });

  it("refuses an order this contract never placed", async () => {
    const res = await handleRelayTx(relayReq(addresses.diamond, cancelData(999_999n)), env);
    expect(res.status).toBe(403);
  });

  it("refuses calldata with a trailing argument smuggled on", async () => {
    const orderId = await placeOrder();
    const padded = (cancelData(BigInt(orderId)) + "0".repeat(64)) as Hex;
    const res = await handleRelayTx(relayReq(addresses.diamond, padded), env);
    expect(res.status).toBe(403);
  });
});

describe.skipIf(!HAS_E2E_FIXTURE)("E2E · the relayer's boundary is structural", () => {
  it("is not a registered merchant, so no funds-moving function is reachable", async () => {
    const registered = await pub.readContract({
      address: addresses.integrator as Address,
      abi: [
        {
          type: "function",
          name: "registered",
          stateMutability: "view",
          inputs: [{ type: "address" }],
          outputs: [{ type: "bool" }],
        },
      ] as const,
      functionName: "registered",
      args: [addresses.relayer as Address],
    });
    expect(registered).toBe(false);
  });

  it("never holds USDC through a real payment", async () => {
    const linkId = await createLink({ id: "e2e-custody", amount: USDC(2) });
    await handlePay(payRequest(), env, linkId);

    const bal = await pub.readContract({
      address: addresses.usdc as Address,
      abi: [
        {
          type: "function",
          name: "balanceOf",
          stateMutability: "view",
          inputs: [{ type: "address" }],
          outputs: [{ type: "uint256" }],
        },
      ] as const,
      functionName: "balanceOf",
      args: [addresses.relayer as Address],
    });
    expect(bal).toBe(0n);
  });

  it("reads link state straight from chain, matching the contract's own view", async () => {
    const linkId = await createLink({ id: "e2e-readthrough", amount: USDC(4), singleUse: true });

    const link = await readLink(pub as never, env, linkId);
    expect(link).not.toBeNull();
    expect(link!.owner.toLowerCase()).toBe(addresses.merchant.toLowerCase());
    expect(link!.amount).toBe(USDC(4));
    expect(linkBlockedReason(link!, Math.floor(Date.now() / 1000))).toBeNull();

    const onChain = await pub.readContract({
      address: addresses.integrator as Address,
      abi: INTEGRATOR_ABI,
      functionName: "isLinkActive",
      args: [linkId],
    });
    expect(onChain).toBe(true);
  });
});

describe.skipIf(!HAS_E2E_FIXTURE)("E2E · gas accounting", () => {
  /** The old daily wei budget, which existed to protect the relayer's float. */
  async function spentWei(): Promise<bigint> {
    const stub = env.GAS_BUDGET.get(env.GAS_BUDGET.idFromName("relayer"));
    const res = await stub.fetch("https://gas/read", {
      method: "POST",
      body: JSON.stringify({ day: Math.floor(Date.now() / 86_400_000) }),
    });
    const { spent } = (await res.json()) as { spent: string };
    return BigInt(spent);
  }

  it("no longer meters a daily wei budget — there is no float to protect", async () => {
    // This test used to assert the opposite, and the inversion is the point.
    //
    // The daily wei ceiling existed because one funded key paid for every
    // payment: without metering, a spam wave drained it and every merchant's
    // links went dark. That key is gone. The sender now holds nothing, gas is
    // sponsored, and spending is bounded by the sponsorship policy BEFORE an
    // operation reaches the chain rather than by us counting after the money
    // has already been spent.
    //
    // Asserting the counter stays at zero pins that the old path really is
    // unused, rather than quietly still signing from the relayer alongside.
    const before = await spentWei();

    const linkId = await createLink({ id: "e2e-gas", amount: USDC(1) });
    const res = await handlePay(payRequest(), env, linkId);
    expect(res.status).toBe(200);

    expect(await spentWei()).toBe(before);
  });

  it("the relayer wallet's balance is untouched by a payment", async () => {
    // The strongest form of the same claim: the funded key is not merely
    // unmetered, it is not spending. When it is deleted at cutover, nothing on
    // this path changes.
    const relayer = privateKeyToAccount(addresses.relayerKey as Hex).address;
    const before = await pub.getBalance({ address: relayer });

    const linkId = await createLink({ id: "e2e-gas-balance", amount: USDC(1) });
    expect((await handlePay(payRequest(), env, linkId)).status).toBe(200);

    expect(await pub.getBalance({ address: relayer })).toBe(before);
  });
});

describe.skipIf(!HAS_E2E_FIXTURE)("E2E · settlement parity", () => {
  it("a link sale lands in the merchant's balance under the normal lock", async () => {
    const linkId = await createLink({ id: "e2e-settle", amount: USDC(3), singleUse: true });
    const res = await handlePay(payRequest(), env, linkId);
    const payload = (await res.json()) as { orderId?: string; error?: string };
    expect(res.status, `pay failed: ${payload.error}`).toBe(200);
    const orderId = payload.orderId!;

    const balBefore = (await pub.readContract({
      address: addresses.integrator as Address,
      abi: [
        {
          type: "function",
          name: "getMerchantBalance",
          stateMutability: "view",
          inputs: [{ type: "address" }],
          outputs: [
            { type: "uint256" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "bool" },
          ],
        },
      ] as const,
      functionName: "getMerchantBalance",
      args: [addresses.merchant as Address],
    })) as readonly [bigint, bigint, bigint, boolean];

    // The LP completes the fiat leg.
    const deployer = createWalletClient({
      account: privateKeyToAccount(
        "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
      ),
      chain,
      transport: http(addresses.rpcUrl),
    });
    const hash = await deployer.writeContract({
      address: addresses.diamond as Address,
      abi: [
        {
          type: "function",
          name: "simulateOrderComplete",
          stateMutability: "nonpayable",
          inputs: [{ type: "uint256" }],
          outputs: [],
        },
      ] as const,
      functionName: "simulateOrderComplete",
      args: [BigInt(orderId)],
      // An EXPLICIT limit, because estimation cannot be trusted for this call.
      // MockDiamond CATCHES a failing onOrderComplete — as the real gateway
      // does — so `eth_estimateGas` binary-searches to the smallest gas that
      // makes the TRANSACTION succeed, which is the amount where the callback
      // is SKIPPED. The order then reads as completed while the USDC sits
      // stranded on the proxy and the merchant is never credited.
      //
      // This surfaced only once the shared node had accumulated enough
      // settlement buckets to make the callback expensive, which is exactly
      // how it would surface in production: fine early, silently wrong later.
      gas: 3_000_000n,
      account: deployer.account!,
      chain,
    });
    await pub.waitForTransactionReceipt({ hash });

    const balAfter = (await pub.readContract({
      address: addresses.integrator as Address,
      abi: [
        {
          type: "function",
          name: "getMerchantBalance",
          stateMutability: "view",
          inputs: [{ type: "address" }],
          outputs: [
            { type: "uint256" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "bool" },
          ],
        },
      ] as const,
      functionName: "getMerchantBalance",
      args: [addresses.merchant as Address],
    })) as readonly [bigint, bigint, bigint, boolean];

    // Pending rises by exactly the sale amount — locked, not yet withdrawable.
    expect(balAfter[0] - balBefore[0]).toBe(USDC(3));
    expect(balAfter[2] - balBefore[2]).toBe(USDC(3));

    // After the lock period it becomes available on the ordinary schedule.
    await increaseTime(addresses.rpcUrl, addresses.settlementPeriod + 10);
    await mineBlocks(addresses.rpcUrl, 1);

    const unlocked = (await pub.readContract({
      address: addresses.integrator as Address,
      abi: [
        {
          type: "function",
          name: "getMerchantBalance",
          stateMutability: "view",
          inputs: [{ type: "address" }],
          outputs: [
            { type: "uint256" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "bool" },
          ],
        },
      ] as const,
      functionName: "getMerchantBalance",
      args: [addresses.merchant as Address],
    })) as readonly [bigint, bigint, bigint, boolean];

    expect(unlocked[1]).toBeGreaterThanOrEqual(USDC(3));
  });
});
